apiVersion: v1
kind: ConfigMap
metadata:
  name: typesense-nodes
data:
  nodes: "typesense-0.typesense-headless:8107:8108,typesense-1.typesense-headless:8107:8108,typesense-2.typesense-headless:8107:8108"
