apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
data:
  # New Relic OTLP endpoint.
  # US: https://otlp.nr-data.net:4318
  # EU: https://otlp.eu01.nr-data.net:4318
  OTEL_EXPORTER_OTLP_ENDPOINT: "https://otlp.eu01.nr-data.net:4318"

  # Override per overlay: deployment.environment=staging|demo
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=staging"
